# Generated by Django 4.2.6 on 2023-10-16 12:38

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_to),
        ),
    ]
